Feature/mvp algo
bat3/Health-Barbecue pull request #67
Opened 2020-05-07 08:31 UTC by bat3

2020-05-07 08:32 UTC, bat3 commented on business/IA/basic_python.py
> +import SimpleITK as sitk
To delete

2020-05-07 10:05 UTC, ptitdam2001 requested changes

2020-05-07 10:05 UTC, ptitdam2001 commented on business/MetadataDatabase/Controllers/AlgoController.cs
> +            return this.algoService.Get(id);
Check if not exists

2020-05-07 10:05 UTC, ptitdam2001 commented on business/MetadataDatabase/Controllers/AlgoController.cs
> +                System.IO.File.WriteAllText(("workspace/algos/" + algo.MainFile), algo.ContentFile);
Maybe I have put the file content into one collection.
In the future, we will be able to add a "code editor" in the frontend to edit and download the algorithm in python file.

2020-05-07 10:05 UTC, ptitdam2001 commented on business/MetadataDatabase/Controllers/AlgoController.cs
> +                System.IO.File.WriteAllText(("workspace/algos/" + algo.MainFile), algo.ContentFile);
I don't know if it is possible to exec an eval of string in Python

2020-05-07 10:05 UTC, ptitdam2001 commented on business/MetadataDatabase/Controllers/Labels/LabelController.cs
> +            return this.labelService.Get(id);
Check if it exists

2020-05-07 10:05 UTC, ptitdam2001 commented on business/MetadataDatabase/Controllers/Labels/LabelController.cs
> +        public ActionResult<LabelDto> Post([FromBody] LabelDto label)
If I were you I verify if the label id is null, I am not sure that to have one void string as ID generates one database Id

2020-05-07 10:05 UTC, ptitdam2001 commented on business/MetadataDatabase/Services/AlgoService.cs
> +            return res.Result;
You should delete unzipped files at the end of execution

2020-05-07 10:05 UTC, ptitdam2001 commented on business/MetadataDatabase/Services/Labels/LabelService.cs
> +            this.labelRepository.Update(objectToUpdate.ToModel());
Should you call IsValid method before update?

2020-05-07 10:05 UTC, ptitdam2001 commented on business/MetadataDatabase/Services/Labels/LabelService.cs
> +            return this.labelRepository.Create(objectToCreate.ToModel()).ToDto();
Should you call IsValid method before create?

2020-05-07 10:05 UTC, ptitdam2001 commented on client/web/src/App.tsx
> +              <Algorithms />
Ah shit!! we will have a conflict with my branch

2020-05-07 10:05 UTC, ptitdam2001 commented on client/web/src/components/algo/AlgoResultDialog.tsx
> +        Algo result
just introduce the T function for translation

2020-05-07 10:05 UTC, ptitdam2001 commented on client/web/src/components/labels/LabelAdding.tsx
> +      setAreInputsValid(true)
simplify with `setAreInputsValid(selectedLabelValue !== '')`

2020-05-07 10:05 UTC, ptitdam2001 commented on client/web/src/components/labels/LabelAdding.tsx
> +    <form>
you can use formik, you will have less code

2020-05-07 10:05 UTC, ptitdam2001 commented on client/web/src/components/labels/LabelCreation.tsx
> +import React, { useState, useEffect } from 'react'
There will be some conflicts with my branch!

2020-05-07 10:05 UTC, ptitdam2001 commented on client/web/src/components/labels/LabelManagementDialog.tsx
> +  const propIsOpen = props.open;
you can use detructuring, for here, you can change by: 

```typescript
const { open: propIsOpen, itemLabelizable, onClose } = props
```
After that you don't need to use the variable props

2020-05-07 10:05 UTC, ptitdam2001 commented on client/web/src/components/labels/LabelManagementDialog.tsx
> +                Create a new label
add t('') function ;)

2020-05-07 12:09 UTC, bat3 commented on business/MetadataDatabase/Controllers/Labels/LabelController.cs
> +        public ActionResult<LabelDto> Post([FromBody] LabelDto label)
id is auto generated by mongo

2020-05-07 12:59 UTC, cquennouelle commented on business/MetadataDatabase/Services/AlgoService.cs
> +            var zipFilzName = this.pacsService.DownloadSeries(algoExeInfo.SeriesInstanceUID);
zipFileName

2020-05-07 12:59 UTC, cquennouelle commented on business/IA/basic_python.py
> +import SimpleITK as sitk
Indeed file in double

2020-05-07 13:15 UTC, bat3 commented on business/MetadataDatabase/Services/Labels/LabelService.cs
> +            this.labelRepository.Update(objectToUpdate.ToModel());
Done after merge develop

2020-05-07 13:15 UTC, bat3 commented on business/MetadataDatabase/Services/Labels/LabelService.cs
> +            return this.labelRepository.Create(objectToCreate.ToModel()).ToDto();
Done after merge develop

2020-05-07 13:28 UTC, bat3 commented on business/MetadataDatabase/Controllers/Labels/LabelController.cs
> +        public ActionResult<LabelDto> Post([FromBody] LabelDto label)
Tested with swagger there is no problems

2020-05-08 13:33 UTC, bat3 commented on business/MetadataDatabase/Controllers/AlgoController.cs
> +                System.IO.File.WriteAllText(("workspace/algos/" + algo.MainFile), algo.ContentFile);
Done

2020-05-08 13:40 UTC, bat3 commented on client/web/src/components/labels/LabelAdding.tsx
> +    <form>
Formik is not working with my changing form...

2020-05-08 19:12 UTC, ptitdam2001 approved these changes

2020-05-09 08:15 UTC, merged